name: iutest

on:
  push:


jobs:
  iutest:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt install g++-11

    - name: Generate object files
      run: |
        find ./ \( -type d -and -name tests -and -prune \) -or \( -type d -and -name iutest_files -and -prune \) -or \( -type f -and -name *.cpp -and -print \) | xargs g++-11 -c -std=c++20 -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest-master/include/

    - name: Run lexical-analyzer test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest-master/include/ ./*.o src/tests/lexical-analyzer.test.cpp
        ./a.out

    - name: Run parser test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest-master/include/ ./*.o src/tests/parser.test.cpp
        ./a.out

    - name: Run evaluator test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest-master/include/ ./*.o src/tests/evaluator.test.cpp
        ./a.out

    - name: Run interpreter test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest-master/include/ ./*.o src/tests/interpreter.test.cpp
        ./a.out