name: iutest

on:
  push:


jobs:
  iutest:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt install g++-11

    - name: Generate object files
      run: |
        make build

    - name: Run lexical-analyzer test
      run: |
        make test TARGET=lexical-analyzer

    - name: Run expression test
      run: |
        make test TARGET=expression

    - name: Run statement test
      run: |
        make test TARGET=statement

    - name: Run parser test
      run: |
        make test TARGET=parser

    - name: Run evaluator test
      run: |
        make test TARGET=evaluator

    - name: Run interpreter test
      run: |
        make test TARGET=interpreter