name: Run tests

on:
  push:


jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        mkdir iutest_files
        cd iutest_files
        wget https://ja.osdn.net/projects/iutest/downloads/73395/iutest-1.17.1.tar.gz
        tar -xvf iutest-1.17.1.tar.gz
        cd ..
        sudo apt install g++-11

    - name: Generate object files
      run: |
        find ./ \( -type d -and -name tests -and -prune \) -or \( -type f -and -name *.cpp -and -print \) | xargs g++-11 -c -std=c++20 -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/

    - name: Run lexical-analyzer test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ ./*.o src/tests/lexical-analyzer.test.cpp
        ./a.out

    - name: Run parser test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ ./*.o src/tests/parser.test.cpp
        ./a.out

    - name: Run evaluator test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ ./*.o src/tests/evaluator.test.cpp
        ./a.out

    - name: Run interpreter test
      run: |
        g++-11 -std=c++20 -Wall -fsplit-stack -fstack-protector-all -fsanitize=undefined -D_GRIBCXX_DEBUG -Wfloat-equal -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ ./*.o src/tests/interpreter.test.cpp
        ./a.out