name: Run tests

on:
  push:


jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        mkdir iutest_files
        cd iutest_files
        wget https://ja.osdn.net/projects/iutest/downloads/73395/iutest-1.17.1.tar.gz
        tar -xvf iutest-1.17.1.tar.gz
        cd ..
        sudo apt install g++-11

    - name: Run lexical-analyzer test
      run: |
        pwd
        ls
        ls ./src/
        g++-11 -std=c++20 -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ src/tests/lexical-analyzer.test.cpp
        ./a.out

    - name: Run parser test
      run: |
        g++-11 -std=c++20 -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ src/tests/parser.test.cpp
        ./a.out

    - name: Run evaluator test
      run: |
        g++-11 -std=c++20 -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ src/tests/evaluator.test.cpp
        ./a.out

    - name: Run interpreter test
      run: |
        g++-11 -std=c++20 -I/home/runner/work/otouto-interpreter/otouto-interpreter/iutest_files/include/ src/tests/interpreter.test.cpp
        ./a.out